import LocalizedStrings from 'react-localization';

let strings = new LocalizedStrings({
    en:{
        label_user:"User",
        label_dashboard:"Dashboard",
        label_responses:"Responses",
        label_insights:"Insights",
        label_sources:"Sources",
        label_settings:"Settings",
        language_english:"English",
        language_german:"German",
        language_french:"French",
        label_selectLanguage:"Select language",
        action_saveChanges:"Save changes",
        label_feedback:"Feedback",
        label_feedbackTopic:"Select topic",
        select_feedbackFeature:"Feature request",
        select_feedbackBug:"Report a bug",
        select_feedbackOther:"Other",
        label_description:"Description",
        label_descriptionDetail:"Enter details...",
        action_feedbackSubmit:"Submit",
        action_close:"Close"
    },
    de:{
        label_user:"Benutzer",
        label_dashboard:"Dashboard",
        label_responses:"Antworten",
        label_insights:"Erkenntnisse",
        label_sources:"Quellen",
        label_settings:"Vertonung",
        language_english:"Englisch",
        language_german:"Deutsche",
        language_french:"Französisch",
        label_selectLanguage:"Sprache auswählen",
        action_saveChanges:"Änderungen speichern",
        label_feedback:"Feedback",
        label_feedbackTopic:"Wählen Sie ein Thema aus",
        select_feedbackFeature:"Featureanfrage",
        select_feedbackBug:"Melde einen technischen Fehler",
        select_feedbackOther:"Andere",
        label_description:"Beschreibung",
        label_descriptionDetail:"Geben Sie Details ein ...",
        action_feedbackSubmit:"Einreichen",
        action_close:"Schließen"
    },
    fr:{
        label_user:"Usager",
        label_dashboard:"Tabl bord",
        label_responses:"Réponses",
        label_insights:"Analyses",
        label_sources:"Sources",
        label_settings:"Paramètres",
        language_english:"Anglais",
        language_german:"Allemand",
        language_french:"Français",
        label_selectLanguage:"Choisir la langue",
        action_saveChanges:"Sauvegarder les modifications",
        label_feedback:"Retour d'information",
        label_feedbackTopic:"Sélectionnez un sujet",
        select_feedbackFeature:"Demande de fonctionnalité",
        select_feedbackBug:"Signaler un bug",
        select_feedbackOther:"Autre",
        label_description:"La description",
        label_descriptionDetail:"Entrez les détails ...",
        action_feedbackSubmit:"Soumettre",
        action_close:"Fermer"
    }    
})

export default strings;